import type { AssetReviewItem } from "./assets";
import type { CatalogPart, ComponentCategory, MockBuild } from "./schemas";

export const componentSteps: Array<{
  id: ComponentCategory | "summary";
  label: string;
  shortLabel: string;
  state: "complete" | "selected" | "warning" | "pending";
}> = [
  { id: "case", label: "機箱", shortLabel: "機箱", state: "complete" },
  {
    id: "motherboard",
    label: "主機板",
    shortLabel: "主機板",
    state: "complete",
  },
  { id: "cpu", label: "處理器", shortLabel: "CPU", state: "complete" },
  { id: "gpu", label: "顯示卡", shortLabel: "GPU", state: "warning" },
  {
    id: "memory",
    label: "記憶體",
    shortLabel: "RAM",
    state: "complete",
  },
  {
    id: "cooling",
    label: "散熱器",
    shortLabel: "散熱",
    state: "complete",
  },
  {
    id: "storage",
    label: "儲存裝置",
    shortLabel: "儲存",
    state: "complete",
  },
  { id: "psu", label: "電源供應器", shortLabel: "PSU", state: "complete" },
  { id: "fans", label: "風扇", shortLabel: "風扇", state: "complete" },
  {
    id: "summary",
    label: "總覽",
    shortLabel: "總覽",
    state: "pending",
  },
];

export const catalogParts: CatalogPart[] = [
  {
    id: "part_case_216",
    sku: "LAN216RX",
    category: "case",
    manufacturer: "Lian Li",
    model: "Lancool 216 RGB Black",
    priceMinor: 84900,
    stockStatus: "in_stock",
    stockCount: 6,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_board_b650",
    sku: "MAG-B650-TOMAHAWK",
    category: "motherboard",
    manufacturer: "MSI",
    model: "MAG B650 Tomahawk WiFi",
    priceMinor: 179900,
    stockStatus: "in_stock",
    stockCount: 4,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_cpu_7800x3d",
    sku: "100-100000910WOF",
    category: "cpu",
    manufacturer: "AMD",
    model: "Ryzen 7 7800X3D",
    priceMinor: 289900,
    stockStatus: "low_stock",
    stockCount: 2,
    assetQuality: "unreviewed",
    assetStatus: "proxy",
    verified: true,
  },
  {
    id: "part_gpu_proart",
    sku: "PROART-RTX4070S-O12G",
    category: "gpu",
    manufacturer: "ASUS",
    model: "ProArt RTX 4070 SUPER",
    priceMinor: 549900,
    stockStatus: "in_stock",
    stockCount: 5,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_gpu_tuf",
    sku: "TUF-RTX4080S-O16G",
    category: "gpu",
    manufacturer: "ASUS",
    model: "TUF RTX 4080 SUPER",
    priceMinor: 789900,
    stockStatus: "low_stock",
    stockCount: 2,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_gpu_zotac",
    sku: "ZT-D40900Q-10P",
    category: "gpu",
    manufacturer: "ZOTAC",
    model: "RTX 4090 Trinity OC",
    priceMinor: 1399900,
    stockStatus: "out_of_stock",
    stockCount: 0,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_memory_32",
    sku: "F5-6000J3038F16GX2",
    category: "memory",
    manufacturer: "G.Skill",
    model: "Flare X5 DDR5-6000 32GB",
    priceMinor: 89900,
    stockStatus: "in_stock",
    stockCount: 9,
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
  },
  {
    id: "part_cooler_ak620",
    sku: "R-AK620-BKNNMT-G",
    category: "cooling",
    manufacturer: "DeepCool",
    model: "AK620 Digital",
    priceMinor: 59900,
    stockStatus: "unknown",
    stockCount: null,
    assetQuality: "draft",
    assetStatus: "needs_review",
    verified: false,
  },
];

export const currentBuild: MockBuild = {
  id: "build_blackout_01",
  name: "1440p 純黑主機",
  selectedPartIds: [
    "part_case_216",
    "part_board_b650",
    "part_cpu_7800x3d",
    "part_gpu_proart",
    "part_memory_32",
    "part_cooler_ak620",
  ],
  warningCount: 1,
  hardErrorCount: 0,
  estimatedWatts: 482,
  totalPriceMinor: 1_284_000,
};

export const reviewAsset: AssetReviewItem = {
  id: "asset_review_fixture",
  part: {
    id: "part_cooler_ak620",
    sku: "R-AK620-BKNNMT-G",
    manufacturer: "DeepCool",
    model: "AK620 Digital",
  },
  status: "in_review",
  quality: "draft",
  sourceKind: "synthetic",
  completedChecks: [
    "model_identity",
    "variant_identity",
    "standard_orientation",
    "verified_dimensions",
    "source_rights",
  ],
  sourceRightsConfirmed: true,
  dimensionsMm: {
    width: 129,
    height: 162,
    depth: 138,
  },
  version: 0,
};
