import type { AssetReviewItem } from "./assets";
import type { CatalogPart, ComponentCategory, MockBuild } from "./schemas";

export const componentSteps: Array<{
  id: ComponentCategory | "summary";
  label: string;
  shortLabel: string;
  state: "complete" | "selected" | "warning" | "pending";
}> = [
  { id: "case", label: "機箱", shortLabel: "機箱", state: "complete" },
  {
    id: "motherboard",
    label: "主機板",
    shortLabel: "主機板",
    state: "complete",
  },
  { id: "cpu", label: "處理器", shortLabel: "CPU", state: "complete" },
  { id: "gpu", label: "顯示卡", shortLabel: "GPU", state: "warning" },
  {
    id: "memory",
    label: "記憶體",
    shortLabel: "RAM",
    state: "complete",
  },
  {
    id: "cooling",
    label: "散熱器",
    shortLabel: "散熱",
    state: "complete",
  },
  {
    id: "storage",
    label: "儲存裝置",
    shortLabel: "儲存",
    state: "complete",
  },
  { id: "psu", label: "電源供應器", shortLabel: "PSU", state: "complete" },
  { id: "fans", label: "風扇", shortLabel: "風扇", state: "complete" },
  {
    id: "summary",
    label: "總覽",
    shortLabel: "總覽",
    state: "pending",
  },
];

export const catalogParts: CatalogPart[] = [
  {
    id: "part_case_fixture_airflow",
    sku: "CASE-FIXTURE-AIRFLOW",
    category: "case",
    manufacturer: "RigStage Fixture",
    model: "ATX Airflow Case",
    priceMinor: 80000,
    stockStatus: "in_stock",
    stockCount: 6,
    specifications: {
      supportedMotherboardFormFactors: "ATX,Micro-ATX,Mini-ITX",
      maxGpuLengthMm: 392,
      maxCoolerHeightMm: 180,
    },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_case_fixture_airflow",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_board_fixture_am5",
    sku: "BOARD-FIXTURE-AM5-ATX",
    category: "motherboard",
    manufacturer: "RigStage Fixture",
    model: "AM5 ATX Board",
    priceMinor: 180000,
    stockStatus: "in_stock",
    stockCount: 4,
    specifications: { socket: "AM5", formFactor: "ATX", memoryType: "DDR5" },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_board_fixture_am5",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_cpu_fixture_am5",
    sku: "CPU-FIXTURE-AM5-8C",
    category: "cpu",
    manufacturer: "RigStage Fixture",
    model: "AM5 8-Core Processor",
    priceMinor: 290000,
    stockStatus: "low_stock",
    stockCount: 2,
    specifications: { socket: "AM5", tdpWatts: 120 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: null,
    assetQuality: "unreviewed",
    assetStatus: "proxy",
    verified: true,
    version: 0,
  },
  {
    id: "part_gpu_fixture_300",
    sku: "GPU-FIXTURE-300-650",
    category: "gpu",
    manufacturer: "RigStage Fixture",
    model: "300 mm Graphics Card",
    priceMinor: 550000,
    stockStatus: "in_stock",
    stockCount: 5,
    specifications: {
      lengthMm: 300,
      slotWidth: 2.5,
      recommendedPsuWatts: 650,
    },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_gpu_fixture_300",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_gpu_fixture_348",
    sku: "GPU-FIXTURE-348-850",
    category: "gpu",
    manufacturer: "RigStage Fixture",
    model: "348 mm Graphics Card",
    priceMinor: 790000,
    stockStatus: "low_stock",
    stockCount: 2,
    specifications: {
      lengthMm: 348,
      slotWidth: 3.65,
      recommendedPsuWatts: 850,
    },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_gpu_fixture_348",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_gpu_fixture_356",
    sku: "GPU-FIXTURE-356-1000",
    category: "gpu",
    manufacturer: "RigStage Fixture",
    model: "356 mm Graphics Card",
    priceMinor: 1400000,
    stockStatus: "out_of_stock",
    stockCount: 0,
    specifications: {
      lengthMm: 356,
      slotWidth: 3.5,
      recommendedPsuWatts: 1000,
    },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_gpu_fixture_356",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_memory_fixture_32",
    sku: "MEMORY-FIXTURE-DDR5-32",
    category: "memory",
    manufacturer: "RigStage Fixture",
    model: "DDR5-6000 32 GB Kit",
    priceMinor: 90000,
    stockStatus: "in_stock",
    stockCount: 9,
    specifications: { memoryType: "DDR5", capacityGb: 32, speedMts: 6000 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_memory_fixture_32",
    assetQuality: "approved",
    assetStatus: "approved",
    verified: true,
    version: 0,
  },
  {
    id: "part_cooling_fixture_162",
    sku: "COOLING-FIXTURE-162",
    category: "cooling",
    manufacturer: "RigStage Fixture",
    model: "162 mm Tower Cooler",
    priceMinor: 60000,
    stockStatus: "unknown",
    stockCount: null,
    specifications: { coolerHeightMm: 162 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: "asset_review_fixture",
    assetQuality: "draft",
    assetStatus: "needs_review",
    verified: false,
    version: 0,
  },
  {
    id: "part_storage_fixture",
    sku: "STORAGE-FIXTURE-1TB",
    category: "storage",
    manufacturer: "RigStage Fixture",
    model: "Verified NVMe 1TB",
    priceMinor: 109900,
    stockStatus: "in_stock",
    stockCount: 8,
    specifications: { interface: "PCIe 4.0 x4", capacityGb: 1000 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: null,
    assetQuality: "unreviewed",
    assetStatus: "proxy",
    verified: true,
    version: 0,
  },
  {
    id: "part_psu_fixture",
    sku: "PSU-FIXTURE-750W",
    category: "psu",
    manufacturer: "RigStage Fixture",
    model: "Verified 750W PSU",
    priceMinor: 99900,
    stockStatus: "in_stock",
    stockCount: 7,
    specifications: { capacityWatts: 750 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: null,
    assetQuality: "unreviewed",
    assetStatus: "proxy",
    verified: true,
    version: 0,
  },
  {
    id: "part_fans_fixture",
    sku: "FANS-FIXTURE-120-3",
    category: "fans",
    manufacturer: "RigStage Fixture",
    model: "Verified 120 mm Fan Kit",
    priceMinor: 39900,
    stockStatus: "in_stock",
    stockCount: 10,
    specifications: { sizeMm: 120, count: 3 },
    specificationStatus: "verified",
    catalogueStatus: "active",
    assetId: null,
    assetQuality: "unreviewed",
    assetStatus: "proxy",
    verified: true,
    version: 0,
  },
];

export const currentBuild: MockBuild = {
  id: "build_fixture_nine_parts",
  name: "九類組件合成示例",
  selectedPartIds: [
    "part_case_fixture_airflow",
    "part_board_fixture_am5",
    "part_cpu_fixture_am5",
    "part_gpu_fixture_300",
    "part_memory_fixture_32",
    "part_cooling_fixture_162",
    "part_storage_fixture",
    "part_psu_fixture",
    "part_fans_fixture",
  ],
  warningCount: 0,
  hardErrorCount: 0,
  estimatedWatts: 482,
  totalPriceMinor: 1_499_700,
};

export const reviewAsset: AssetReviewItem = {
  id: "asset_review_fixture",
  part: {
    id: "part_cooling_fixture_162",
    sku: "COOLING-FIXTURE-162",
    manufacturer: "RigStage Fixture",
    model: "162 mm Tower Cooler",
  },
  status: "in_review",
  quality: "draft",
  sourceKind: "synthetic",
  completedChecks: [
    "model_identity",
    "variant_identity",
    "standard_orientation",
    "verified_dimensions",
    "source_rights",
  ],
  sourceRightsConfirmed: true,
  files: {
    sources: {
      front: null,
      back: null,
      left: null,
      "three-quarter": null,
    },
    model: null,
  },
  dimensionsMm: {
    width: 129,
    height: 162,
    depth: 138,
  },
  version: 0,
};

export const reviewQueueAssets: AssetReviewItem[] = [
  reviewAsset,
  {
    ...reviewAsset,
    id: "asset_review_fixture_secondary",
    part: {
      id: "part_cooling_fixture_240",
      sku: "COOLING-FIXTURE-240",
      manufacturer: "RigStage Fixture",
      model: "240 mm Liquid Cooler",
    },
    status: "draft",
    quality: "unreviewed",
    sourceKind: "uploaded",
    completedChecks: [],
    sourceRightsConfirmed: false,
    dimensionsMm: { width: null, height: null, depth: null },
  },
];
